FROM docker.io/nagadomi/torch7:latest

#Fixing github directory issue
RUN git config --global url.https://github.com/.insteadOf git://github.com/

#Setting up tz
ENV TZ=Europe/Minsk
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt-get update && apt-get install

RUN luarocks install matio

#OpenCV
# Install minimal prerequisites (Ubuntu 18.04 as reference)
#RUN sudo apt install -y cmake g++ wget unzip
# Download and unpack sources
#RUN git clone https://github.com/opencv/opencv.git && git -C opencv checkout 3.1.0
#RUN apt-get -y upgrade && echo "deb http://us.archive.ubuntu.com/ubuntu/ yakkety universe" | sudo tee -a /etc/apt/sources.list
#Missing libjasper-dev 
#RUN apt-get -y install apt-utils ffmpeg libopencv-dev libgtk-3-dev python-numpy python3-numpy libdc1394-22 libdc1394-22-dev libjpeg-dev libpng-dev libtiff5-dev libavcodec-dev libavformat-dev libswscale-dev libxine2-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libv4l-dev libtbb-dev qtbase5-dev libfaac-dev libmp3lame-dev libopencore-amrnb-dev libopencore-amrwb-dev libtheora-dev libvorbis-dev libxvidcore-dev x264 v4l-utils unzip
#RUN cd opencv && mkdir -p build && cd build && cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -D WITH_TBB=ON -D WITH_V4L=ON -D WITH_QT=ON -D WITH_OPENGL=ON -D WITH_JASPER=ON -D CUDA_nppi_LIBRARY=true /root/opencv/ 
RUN sudo apt-get -y install build-essential
RUN sudo apt-get -y install cmake git libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev
RUN sudo apt-get -y install python-dev python-numpy libtbb2 libtbb-dev libjpeg-dev libpng-dev libtiff-dev libdc1394-22-dev
RUN git clone https://github.com/opencv/opencv.git && git -C opencv checkout 3.1.0
RUN cd opencv && mkdir -p build && cd build && cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -D WITH_TBB=ON -D WITH_V4L=ON -D WITH_QT=ON -D WITH_OPENGL=ON -D WITH_JASPER=ON -D CUDA_nppi_LIBRARY=true -D ENABLE_PRECOMPILED_HEADERS=OFF /root/opencv/ && make -j7 && sudo make install

##CV install 
RUN luarocks install cv